FROM node:10.13.0-slim
MAINTAINER tooget <tooget@gmailcom>

COPY . /FitoDapp
WORKDIR /FitoDapp

RUN apt-get update
RUN apt-get install git-core -y
RUN npm install
RUN npm install -g truffle ganache-cli lite-server

CMD ["ganache-cli","-q"]
CMD ["truffle build"]
CMD ["truffle migrate"]
CMD ["lite-server"]

EXPOSE 8545
EXPOSE 3000
